package fr.flegac.jstory.stories.publisher_Features.publisher;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.assertj.core.api.Assertions;
import org.junit.Test;
import fr.flegac.jstory.Epic;
import fr.flegac.jstory.Story;
import fr.flegac.jstory.parser.CodeStoryParser;
import fr.flegac.jstory.parser.JarStoryParser;
import fr.flegac.jstory.parser.StoryParser;
import fr.flegac.jstory.parser.model.PublicationDTO;
import fr.flegac.jstory.publisher.web.WebPublisher;
import fr.flegac.jstory.publisher.web.WebTemplate;

@Epic(why = "publish user stories from source code",
      who = "publisher",
      what = "run a publishing program and generate all stories defined in functional test classes")
public class PublisherStories {

  private static final Path WORKSPACE = Paths.get(System.getProperty("user.dir"));
  private static final Path WEB_TEMPLATE = WORKSPACE.resolve("src/main/resources/web-template");
  private static final Path outputSource = WORKSPACE.resolve("target/outputSource");
  private static final Path outputJar = WORKSPACE.resolve("target/outputJar");

  private static final Path JAR_PATH = WORKSPACE.resolve("src/test/java/jstory-doc-0.0.1-SNAPSHOT.jar");
  private static final String INDEX_HTML = "index.html";
  private static final String STORIES_PACKAGE = "fr.flegac.jstory.stories";

  @Test
  @Story(why = "generate specifications from source code",
         who = "developper",
         what = "parse source code containing specifications and generate a web site from it")
  @Story(why = "verify that 2 @Story annotations can be on the same test method",
         who = "developper",
         what = "assign multiple @Story annotations to a single test method")
  public void publishFromCode() throws Exception {
    publish(new CodeStoryParser(STORIES_PACKAGE), outputSource);
  }

  @Test
  @Story(why = "generate specifications from jar file",
         who = "developper",
         what = "parse a given jar file containing java code with specifications and genrate a web site wfrom it")
  public void publishFromJar() throws Exception {
    publish(new JarStoryParser(STORIES_PACKAGE, JAR_PATH), outputJar);
  }

  private void publish(final StoryParser parser, final Path output) throws IOException {
    final PublicationDTO publication = parser.getPublication("Autogenerated User Stories of the JStory project");
    final WebTemplate template = new WebTemplate(WEB_TEMPLATE);
    final WebPublisher publisher = new WebPublisher(template);
    publisher.publish(publication, output);
    System.out.println(output);
    Assertions.assertThat(output).exists();
    Assertions.assertThat(output.resolve(INDEX_HTML)).exists();
  }
}
